export const TUNINGS = [
  {
    name: 'Standard',
    strings: [
      { stringNumber: 1, rootNote: 'E', octave: 4 },
      { stringNumber: 2, rootNote: 'B', octave: 3 },
      { stringNumber: 3, rootNote: 'G', octave: 3 },
      { stringNumber: 4, rootNote: 'D', octave: 3 },
      { stringNumber: 5, rootNote: 'A', octave: 2 },
      { stringNumber: 6, rootNote: 'E', octave: 2 },
    ],
  },
  {
    name: 'Bass Standard',
    strings: [
      { stringNumber: 1, rootNote: 'B' },
      { stringNumber: 2, rootNote: 'G' },
      { stringNumber: 3, rootNote: 'A' },
      { stringNumber: 4, rootNote: 'E' },
    ],
  },
  {
    name: 'Half-Step Down',
    strings: [
      { stringNumber: 1, rootNote: 'D#' },
      { stringNumber: 2, rootNote: 'A#' },
      { stringNumber: 3, rootNote: 'F#' },
      { stringNumber: 4, rootNote: 'C#' },
      { stringNumber: 5, rootNote: 'G#' },
      { stringNumber: 6, rootNote: 'D#' },
    ],
  },
  {
    name: 'Drop D',
    strings: [
      { stringNumber: 1, rootNote: 'E' },
      { stringNumber: 2, rootNote: 'B' },
      { stringNumber: 3, rootNote: 'G' },
      { stringNumber: 4, rootNote: 'D' },
      { stringNumber: 5, rootNote: 'A' },
      { stringNumber: 6, rootNote: 'D' },
    ],
  },
  {
    name: 'DADGAD',
    strings: [
      { stringNumber: 1, rootNote: 'D' },
      { stringNumber: 2, rootNote: 'A' },
      { stringNumber: 3, rootNote: 'G' },
      { stringNumber: 4, rootNote: 'D' },
      { stringNumber: 5, rootNote: 'A' },
      { stringNumber: 6, rootNote: 'D' },
    ],
  },
  {
    name: 'Drop C#',
    strings: [
      { stringNumber: 1, rootNote: 'D#' },
      { stringNumber: 2, rootNote: 'A#' },
      { stringNumber: 3, rootNote: 'F#' },
      { stringNumber: 4, rootNote: 'C#' },
      { stringNumber: 5, rootNote: 'G#' },
      { stringNumber: 6, rootNote: 'C#' },
    ],
  },
  {
    name: 'Drop C',
    strings: [
      { stringNumber: 1, rootNote: 'D' },
      { stringNumber: 2, rootNote: 'A' },
      { stringNumber: 3, rootNote: 'F' },
      { stringNumber: 4, rootNote: 'C' },
      { stringNumber: 5, rootNote: 'G' },
      { stringNumber: 6, rootNote: 'C' },
    ],
  },
  {
    name: '7 String Standard',
    strings: [
      { stringNumber: 1, rootNote: 'E' },
      { stringNumber: 2, rootNote: 'B' },
      { stringNumber: 3, rootNote: 'G' },
      { stringNumber: 4, rootNote: 'D' },
      { stringNumber: 5, rootNote: 'A' },
      { stringNumber: 6, rootNote: 'E' },
      { stringNumber: 7, rootNote: 'B' },
    ],
  },
  {
    name: '8 String Standard',
    strings: [
      { stringNumber: 1, rootNote: 'E' },
      { stringNumber: 2, rootNote: 'B' },
      { stringNumber: 3, rootNote: 'G' },
      { stringNumber: 4, rootNote: 'D' },
      { stringNumber: 5, rootNote: 'A' },
      { stringNumber: 6, rootNote: 'E' },
      { stringNumber: 7, rootNote: 'B' },
      { stringNumber: 8, rootNote: 'F#' },
    ],
  },
  {
    name: '12 String Standard',
    strings: [
      { stringNumber: 1, rootNote: 'E', octave: 5 },
      { stringNumber: 2, rootNote: 'E', octave: 4 },
      { stringNumber: 3, rootNote: 'B', octave: 4 },
      { stringNumber: 4, rootNote: 'B', octave: 3 },
      { stringNumber: 5, rootNote: 'G', octave: 4 },
      { stringNumber: 6, rootNote: 'G', octave: 3 },
      { stringNumber: 7, rootNote: 'D', octave: 4 },
      { stringNumber: 8, rootNote: 'D', octave: 3 },
      { stringNumber: 9, rootNote: 'A', octave: 3 },
      { stringNumber: 10, rootNote: 'A', octave: 2 },
      { stringNumber: 11, rootNote: 'E', octave: 3 },
      { stringNumber: 12, rootNote: 'E', octave: 2 },
    ],
  },
];
